data("USArrests")
df<-scale(USArrests)
install.packages("factoextra")
set.seed(0)
fviz_nbclust(df, kmeans, method="wss", print.summary = TRUE)
set.seed(123)
km.res<-kmeans(df,6,nstart=25)
print(km.res)
df_fin<-cbind(USArrests,cluster=km.res$cluster)
fviz_cluster(km.res,df,ellipse = TRUE,show.clust.cent = TRUE,ellipse.type = "convex")
install.packages("fpc")
fviz_nbclust(df,cluster::pam)
pam.res<-pam(df,2)
fviz_cluster(pam.res)
pairs(df)
fviz_cluster(km.res,df,choose.vars = c("Murder","Assault"),ellipse=TRUE)
cor(df)

